### ISSUE TITLE
remote issue

### ISSUE THREAD

**Issue by dunk8888** [nlamprian/IRRemoteControl#1]
Hi ive tryed to add my own remote codes from a remote,and it doesnt seem to work,my codes are shorter than the codes in this library,they are like this 0xffddtt but i see your remote has 0x10ddfftt.Why does your code have 10 each time in the code? I think my remote is nec.

**Comment by nlamprian** [comment]
These are the codes for my [remote](https://www.sparkfun.com/products/11759). If you are not sure about the codes of your remote, if think the IRremote library has some code to help you identify them.

**Comment by dunk8888** [comment]
Hi ive emailed the guy who wrote the library,ime waiting on a reply,ive
tryed to change the codes to my codes but wont work,it says you can but it
depends on the remote code type like sony or nec etc,thanks
